name: Build Docker Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - name: Run Tests
        run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - name: Build OpenKMS CLI
        run: docker build . --file .docker/cli/Dockerfile --tag open-kms-cli:0.0.1
      - name: Build OpenKMS Daemon
        run: docker build . --file .docker/daemon/Dockerfile --tag open-kms-daemon:0.0.1
