name: Build Docker Images

on:
  push:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - name: Run Tests
        run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.CR_PAT }}
      - name: Build OpenKMS CLI
        run: docker build . --file .docker/cli/Dockerfile --tag ghcr.io/hyperplane-sh/openkms:cli-0.0.1
      - name: Build OpenKMS Daemon
        run: docker build . --file .docker/daemon/Dockerfile --tag ghcr.io/hyperplane-sh/openkms:daemon-0.0.1
      - name: Push OpenKMS CLI
        run: docker push ghcr.io/hyperplane-sh/openkms:cli-0.0.1
      - name: Push OpenKMS Daemon
        run: docker push ghcr.io/hyperplane-sh/openkms:daemon-0.0.1