name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build OpenKMS CLI
      run: docker build . --file .docker/cli/Dockerfile --tag open-kms-cli:0.0.1
